dist: bionic
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "nightly"

addons:
  apt:
    packages:
    # This is required to run chromium
    - libgbm1
    - libgles2
    - gstreamer1.0-libav

matrix:
  allow_failures:
    - python: "nightly"

install:
  - pip install pytest

before_script:
  - "pip install -r requirements.txt"
  - "python setup.py install_lib"
  - "python -m playwright install"

script:
  - pytest tests