dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

matrix:
  allow_failures:
    - python: "3.8-dev"
    - python: "nightly"

addons:
  firefox: "62.0.3"

install:
  - pip install pytest

before_script:
  - "wget https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux64.tar.gz -O /tmp/geckodriver.tar.gz && tar -C /opt -xzf /tmp/geckodriver.tar.gz && sudo chmod 755 /opt/geckodriver && sudo ln -fs /opt/geckodriver /usr/bin/geckodriver && sudo ln -fs /opt/geckodriver /usr/local/bin/geckodriver"
  - "sudo apt-get install java-common"
  - "pip install -r requirements.txt"
  - "sudo apt-get install unzip"
  - "wget https://github.com/lightbody/browsermob-proxy/releases/download/browsermob-proxy-2.1.4/browsermob-proxy-2.1.4-bin.zip -O /tmp/browsermob-proxy.zip && unzip /tmp/browsermob-proxy.zip && mv -f browsermob-proxy-2.1.4 browsermob-proxy"
  - "python setup.py install_lib"

script:
  - pytest tests/test_trending.py
