dist: xenial
language: python
python:
  - "3.7"

matrix:
  allow_failures:
    - python: "3.8-dev"
    - python: "nightly"

addons:
  firefox: "62.0.3"
  chrome: stable

install:
  - pip install TikTokApi pytest
  - pip install -r requirements.txt

language: python
python:
  - "3.7"

script:
  - pytest tests/test_trending.py
