dist: xenial
language: python
python:
  - "3.7"

matrix:
  allow_failures:
    - python: "3.8-dev"
    - python: "nightly"

addons:
  firefox: "62.0.3"
  # chrome: stable

install:
  # - pip install seleniumbase
  - pip install pytest

language: python
python:
  - "3.7"

before_script:
  # - "flake8 --exclude=temp"
  # - "wget https://chromedriver.storage.googleapis.com/2.44/chromedriver_linux64.zip && unzip chromedriver_linux64.zip && sudo cp chromedriver /usr/local/bin/ && sudo chmod +x /usr/local/bin/chromedriver"
  - "wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz -O /tmp/geckodriver.tar.gz && tar -C /opt -xzf /tmp/geckodriver.tar.gz && sudo chmod 755 /opt/geckodriver && sudo ln -fs /opt/geckodriver /usr/bin/geckodriver && sudo ln -fs /opt/geckodriver /usr/local/bin/geckodriver"
  # - "wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 && tar -xvf ./phantomjs-2.1.1-linux-x86_64.tar.bz2 && export PATH=$PWD/phantomjs-2.1.1-linux-x86_64/bin:$PATH"
  # - "seleniumbase install geckodriver"
  # - "wget https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux64.tar.gz -o /tmp/geckodriver.tar.gz && tar -C /opt -xzf /tmp/geckodriver.tar.gz && sudo chmod 755 /opt/geckodriver && sudo ln -fs /opt/geckodriver /usr/bin/geckodriver && sudo ln -fs /opt/geckodriver /usr/local/bin/geckodriver"
  # - python setup.py build
  - "sudo apt-get install java-common"
  - "pip install -r requirements.txt"
  - "sudo apt-get install unzip"
  - "wget https://github.com/lightbody/browsermob-proxy/releases/download/browsermob-proxy-2.1.4/browsermob-proxy-2.1.4-bin.zip -O /tmp/browsermob-proxy.zip && unzip /tmp/browsermob-proxy.zip && mv -f browsermob-proxy-2.1.4 browsermob-proxy"
  # - "wget https://github.com/lightbody/browsermob-proxy/releases/download/browsermob-proxy-2.1.4/browsermob-proxy-2.1.4-bin.zip -O /tmp/browsermob-proxy.zip && unzip /tmp/browsermob-proxy.zip -d davidteather/TikTok-Api/ && mv -f davidteather/TikTok-Api/browsermob-proxy-2.1.4 davidteather/TikTok-Api/browsermob-proxy"
  - "python setup.py install_lib"

script:
  - pytest tests/test_trending.py
