dist: bionic
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "nightly"

addons:
  apt:
    packages:
    # These are required to run webkit
    - libwoff1
    - libopus0
    - libwebp6
    - libwebpdemux2
    - libenchant1c2a
    - libgudev-1.0-0
    - gstreamer1.0-libav
    - libsecret-1-0
    - libhyphen0
    - libgdk-pixbuf2.0-0
    - libegl1
    - libgles2
    - libevent-2.1-6
    - libnotify4
    - libxslt1.1
    - libvpx5

matrix:
  allow_failures:
    - python: "nightly"

install:
  - pip install pytest
  - "pip install -r requirements.txt"
  - "python setup.py install_lib"
  - python -m playwright install

script:
  - pytest tests