name: TikTokApi CI

on:
  pull_request:
  branches:

jobs:
    build:
      runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.7.3
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.3
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Run Tests
      run: |
        pytest tests